package com.cydeo.entity;

import lombok.*;
import org.hibernate.validator.constraints.Currency;

import javax.persistence.*;
import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@MappedSuperclass // to extend by other classes
public class BaseEntity {
//  we need this information because the app should record these activities
//  this info is for BD

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // to be generated by spring
    private Long id;

    @Column(nullable = false, updatable = false)
    private LocalDateTime insertDateTime;
    @Column(nullable = false, updatable = false)
    private Long insertUserId;
    private LocalDateTime lastUpdateDateTime;
    @Column(nullable = false)
    private Long lastUpdateUserId;

    @Column(nullable = false)
    private Boolean isDeleted= false;



    @PrePersist
    private void onPrePersist(){
        this.insertDateTime=LocalDateTime.now();
        this.lastUpdateDateTime=LocalDateTime.now();
        this.insertUserId=1L;
        this.lastUpdateUserId=1L;
    }
    @PreUpdate
    private void onPreUpdate(){

        this.lastUpdateDateTime=LocalDateTime.now();
        this.lastUpdateUserId=1L;
    }


}
